#!/bin/bash


cat=$(curl -s "https://api.thecatapi.com/v1/images/search" | jq '.[0].url' | tr -d \")

curl -s -o /home/magdalena/2rok1semestr/akiso/lista4/cat.jpg "$cat"

catimg -l 0 /home/magdalena/2rok1semestr/akiso/lista4/cat.jpg

rm /home/magdalena/2rok1semestr/akiso/lista4/cat.jpg

chuck_jokes=$(curl -s "https://api.chucknorris.io/jokes/random" | jq '.value' | tr -d \")
echo ${chuck_jokes}
